### ISSUE TITLE
有bug,重开会闪退

### ISSUE THREAD

**Issue by wengxianxun** [idootop/fallDown#1]
有bug,重开会闪退

**Comment by idootop** [comment]
无法复现，请详细说明问题触发步骤，或提供录屏给我。

**Comment by wengxianxun** [comment]
E/flutter (14593): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Concurrent modification during iteration: Instance(length:13) of '_GrowableList'.
E/flutter (14593): #0      ListIterator.moveNext (dart:_internal/iterable.dart:337:7)
E/flutter (14593): #1      ExpandIterator.moveNext (dart:_internal/iterable.dart:481:32)
E/flutter (14593): #2      IterableMixin.forEach (dart:collection/iterable.dart:44:23)
E/flutter (14593): #3      MyGame.killAll (package:flutter_app2/game/myGame.dart:325:10)
E/flutter (14593): #4      _MainPageState.newGame (package:flutter_app2/main.dart:97:10)
E/flutter (14593): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (14593): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (14593): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (14593): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (14593): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (14593): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter (14593): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter (14593): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (14593): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (14593): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (14593): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (14593): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (14593): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter (14593): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (14593): #19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (14593): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (14593): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (14593): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (14593): #23     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (14593): #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (14593): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (14593): #26     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (14593): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (14593):

**Comment by wengxianxun** [comment]
https://user-images.githubusercontent.com/831898/109012511-0e0d2000-76ed-11eb-9c8b-31f81424fc8d.mp4

**Comment by wengxianxun** [comment]
已上传， 一局结束点击重新开始就黑屏了，   华为p20

**Comment by idootop** [comment]
> E/flutter (14593): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Concurrent modification during iteration: Instance(length:13) of '_GrowableList'.
> E/flutter (14593): #0 ListIterator.moveNext (dart:_internal/iterable.dart:337:7)
> E/flutter (14593): #1 ExpandIterator.moveNext (dart:_internal/iterable.dart:481:32)
> E/flutter (14593): #2 IterableMixin.forEach (dart:collection/iterable.dart:44:23)
> E/flutter (14593): #3 MyGame.killAll (package:flutter_app2/game/myGame.dart:325:10)
> E/flutter (14593): #4 _MainPageState.newGame (package:flutter_app2/main.dart:97:10)
> E/flutter (14593): #5 _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
> E/flutter (14593): #6 _InkResponseState.build. (package:flutter/src/material/ink_well.dart:1111:38)
> E/flutter (14593): #7 GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
> E/flutter (14593): #8 TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
> E/flutter (14593): #9 BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
> E/flutter (14593): #10 BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
> E/flutter (14593): #11 PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
> E/flutter (14593): #12 PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
> E/flutter (14593): #13 PointerRouter._dispatchEventToRoutes. (package:flutter/src/gestures/pointer_router.dart:122:9)
> E/flutter (14593): #14 _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
> E/flutter (14593): #15 PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
> E/flutter (14593): #16 PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
> E/flutter (14593): #17 GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
> E/flutter (14593): #18 GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
> E/flutter (14593): #19 RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
> E/flutter (14593): #20 GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
> E/flutter (14593): #21 GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
> E/flutter (14593): #22 GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
> E/flutter (14593): #23 _rootRunUnary (dart:async/zone.dart:1206:13)
> E/flutter (14593): #24 _CustomZone.runUnary (dart:async/zone.dart:1100:19)
> E/flutter (14593): #25 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
> E/flutter (14593): #26 _invoke1 (dart:ui/hooks.dart:265:10)
> E/flutter (14593): #27 _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
> E/flutter (14593):

感谢反馈，经测试，已修复。
